unbind r
bind r source-file ~/.tmux/tmux.conf

set -g prefix C-a

set -g mouse on

set -g base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'


# --- Color Themes ---
# Catppuccin
# set -g @catppuccin_flavor "macchiato"
# set -g @catppuccin_status_background "none"
# set -g @catppuccin_window_status_style "none"
# set -g @catppuccin_pane_status_enabled "no"
# set -g @catppuccin_pane_border_status "no"
# Nord
set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
